<a href="https://colab.research.google.com/github/Philippe-AD/Jupyter/blob/master/Bot_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
sentences = [
'Alexa, ask Roomba to start vacuuming',
'Alexa, ask Braava to start mopping',
'Alexa, tell Roomba to stop vacuuming',
'Alexa, tell Braava to stop sweeping'   
]

input ="Alexa, ask Roomba to start vacuuming"
if input == "Alexa, ask Roomba to start vacuuming":
  numero = 1, 'call start vacuuming'
if input == "Alexa, tell Roomba to stop vacuuming":
  numero = 3, 'call stop vacuuming'

print(numero)  

(1, 'call start vacuuming')


In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [8]:
import nltk

word_data = "The best performance can bring in sky high success."+'Alexa, ask Roomba to start vacuuming'+'Alexa, ask Braava to start mopping'+'Alexa, tell Roomba to stop vacuuming'
'Alexa, tell Braava to stop sweeping'   
nltk_tokens = nltk.word_tokenize(word_data)  	

print(list(nltk.bigrams(nltk_tokens)))

[('The', 'best'), ('best', 'performance'), ('performance', 'can'), ('can', 'bring'), ('bring', 'in'), ('in', 'sky'), ('sky', 'high'), ('high', 'success.Alexa'), ('success.Alexa', ','), (',', 'ask'), ('ask', 'Roomba'), ('Roomba', 'to'), ('to', 'start'), ('start', 'vacuumingAlexa'), ('vacuumingAlexa', ','), (',', 'ask'), ('ask', 'Braava'), ('Braava', 'to'), ('to', 'start'), ('start', 'moppingAlexa'), ('moppingAlexa', ','), (',', 'tell'), ('tell', 'Roomba'), ('Roomba', 'to'), ('to', 'stop'), ('stop', 'vacuuming')]


In [9]:
from collections import Counter

def bigram_counts(word_list):
	bgs = nltk.bigrams(word_list)
	fdist = nltk.FreqDist(bgs)
	d = Counter()
	for k, v in fdist.items():
		d[k] = v
	return d 

print(bigram_counts(nltk_tokens))  

Counter({(',', 'ask'): 2, ('Roomba', 'to'): 2, ('to', 'start'): 2, ('The', 'best'): 1, ('best', 'performance'): 1, ('performance', 'can'): 1, ('can', 'bring'): 1, ('bring', 'in'): 1, ('in', 'sky'): 1, ('sky', 'high'): 1, ('high', 'success.Alexa'): 1, ('success.Alexa', ','): 1, ('ask', 'Roomba'): 1, ('start', 'vacuumingAlexa'): 1, ('vacuumingAlexa', ','): 1, ('ask', 'Braava'): 1, ('Braava', 'to'): 1, ('start', 'moppingAlexa'): 1, ('moppingAlexa', ','): 1, (',', 'tell'): 1, ('tell', 'Roomba'): 1, ('to', 'stop'): 1, ('stop', 'vacuuming'): 1})


In [10]:
def trigram_counts(word_list):
	tgs = nltk.trigrams(word_list)
	fdist = nltk.FreqDist(tgs)
	d = Counter()
	for k, v in fdist.items():
		d[k] = v
	return d

print(trigram_counts(nltk_tokens))    

Counter({('The', 'best', 'performance'): 1, ('best', 'performance', 'can'): 1, ('performance', 'can', 'bring'): 1, ('can', 'bring', 'in'): 1, ('bring', 'in', 'sky'): 1, ('in', 'sky', 'high'): 1, ('sky', 'high', 'success.Alexa'): 1, ('high', 'success.Alexa', ','): 1, ('success.Alexa', ',', 'ask'): 1, (',', 'ask', 'Roomba'): 1, ('ask', 'Roomba', 'to'): 1, ('Roomba', 'to', 'start'): 1, ('to', 'start', 'vacuumingAlexa'): 1, ('start', 'vacuumingAlexa', ','): 1, ('vacuumingAlexa', ',', 'ask'): 1, (',', 'ask', 'Braava'): 1, ('ask', 'Braava', 'to'): 1, ('Braava', 'to', 'start'): 1, ('to', 'start', 'moppingAlexa'): 1, ('start', 'moppingAlexa', ','): 1, ('moppingAlexa', ',', 'tell'): 1, (',', 'tell', 'Roomba'): 1, ('tell', 'Roomba', 'to'): 1, ('Roomba', 'to', 'stop'): 1, ('to', 'stop', 'vacuuming'): 1})


In [ ]:
«Alexa, démarre la machine à café Home Connect» ou «Alexa, dis à la machine à café Home Connect de démarrer». 
Alexa entame le dialogue immédiatement, et vous guide tout au long des étapes.

Si vous maîtrisez déjà la compétence, essayez de faire une demande plus complexe; par exemple: 
«Alexa, dis à la machine à café Home Connect de faire un cappuccino.». 
Ce raccourci vous permet de sélectionner votre café préféré rapidement et directement en une seule phrase. 
Pour cela, la machine à café utilise les derniers réglages utilisés pour la contenance et la force.

Si vous avez une préférence personnelle pour le café, donnez directement toutes les indications: 
«Alexa, dis à la machine à café Home Connect de faire un grand cappuccino très serré.». 

Si Alexa ne comprends pas correctement tous les mots, l'Assistant vient automatiquement à votre rescousse.

Il se peut également que la machine à café soit en veille au moment de votre demande. Dans ce cas, la machine à café démarre automatiquement et lance le cycle de rinçage. 
Patientez quelques minutes jusqu'à la fin du cycle et recommencez.

Voici quelques conseils: si vous ne savez pas exactement quoi dire pendant un dialogue, attendez quelques secondes, 
Alexa fera automatiquement quelques suggestions. Vous pouvez mettre fin au dialogue quand vous le souhaitez en disant «Interrompre» ou «Arrêter».

Voir Intro-to-NLP.ipynb

In [ ]:
{'ROOMBA': {'START': ['Alexa, ask Roomba to start vacuuming',
   'Alexa, ask Braava to start mopping'],
  'STOP': ['Alexa, tell Roomba to stop vacuuming',
   'Alexa, tell Braava to stop sweeping']}}

'Alexa, ask Roomba to start vacuuming',
'Alexa, ask Braava to start mopping',
'Alexa, tell Roomba to stop vacuuming',
'Alexa, tell Braava to stop sweeping'   

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences  # We will use it later

sentences = [
'Alexa, ask Roomba to start vacuuming',
'Alexa, ask Braava to start mopping',
'Alexa, tell Roomba to stop vacuuming',
'Alexa, tell Braava to stop sweeping',
'Ok Google, quelles sont les actualités ?',
'Ok Google, quelles sont les actualités économiques ?',
'Ok Google, quelles sont les actualités technologie ?'   
]

# Create object of Tokenizer and tokenize sentences
tokenizer = Tokenizer(num_words = 100)  # max distinct words first 100 words
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index  # returns dictionary
print(word_index)

{'alexa': 1, 'to': 2, 'ok': 3, 'google': 4, 'quelles': 5, 'sont': 6, 'les': 7, 'actualités': 8, 'ask': 9, 'roomba': 10, 'start': 11, 'vacuuming': 12, 'braava': 13, 'tell': 14, 'stop': 15, 'mopping': 16, 'sweeping': 17, 'économiques': 18, 'technologie': 19}


In [ ]:
import pprint
# at Tokenizer instance creation add another keyword argument
tokenizer = Tokenizer(num_words=100, oov_token='<OOv>')  # OOV means Out of vocabulary

tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index
sequences=tokenizer.texts_to_sequences(sentences)

pprint.pprint(word_index)
print("\nTest Sequence = ")
pprint.pprint(sequences)



{'<OOv>': 1,
 'actualités': 9,
 'alexa': 2,
 'ask': 10,
 'braava': 14,
 'google': 5,
 'les': 8,
 'mopping': 17,
 'ok': 4,
 'quelles': 6,
 'roomba': 11,
 'sont': 7,
 'start': 12,
 'stop': 16,
 'sweeping': 18,
 'technologie': 20,
 'tell': 15,
 'to': 3,
 'vacuuming': 13,
 'économiques': 19}

Test Sequence = 
[[2, 10, 11, 3, 12, 13],
 [2, 10, 14, 3, 12, 17],
 [2, 15, 11, 3, 16, 13],
 [2, 15, 14, 3, 16, 18],
 [4, 5, 6, 7, 8, 9],
 [4, 5, 6, 7, 8, 9, 19],
 [4, 5, 6, 7, 8, 9, 20]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(sequences, padding='pre',truncating='post',maxlen=15)
print(padded_sequences)

[[ 0  0  0  0  0  0  0  0  0  2 10 11  3 12 13]
 [ 0  0  0  0  0  0  0  0  0  2 10 14  3 12 17]
 [ 0  0  0  0  0  0  0  0  0  2 15 11  3 16 13]
 [ 0  0  0  0  0  0  0  0  0  2 15 14  3 16 18]
 [ 0  0  0  0  0  0  0  0  0  4  5  6  7  8  9]
 [ 0  0  0  0  0  0  0  0  4  5  6  7  8  9 19]
 [ 0  0  0  0  0  0  0  0  4  5  6  7  8  9 20]]


In [ ]:
# inverse mapping using zip and dict functions 
inv_dict = dict(zip(word_index.values(), word_index.keys())) 

# print final dictionary 
print("inverse mapped dictionary : ")
pprint.pprint(str(inv_dict)) 
print(inv_dict[2]) 

inverse mapped dictionary : 
("{1: '<OOv>', 2: 'alexa', 3: 'to', 4: 'ok', 5: 'google', 6: 'quelles', 7: "
 "'sont', 8: 'les', 9: 'actualités', 10: 'ask', 11: 'roomba', 12: 'start', 13: "
 "'vacuuming', 14: 'braava', 15: 'tell', 16: 'stop', 17: 'mopping', 18: "
 "'sweeping', 19: 'économiques', 20: 'technologie'}")
alexa




---



In [ ]:
pip install -q tensorflow

In [ ]:
pip install -q tensorflow-text

In [ ]:
import tensorflow as tf
import tensorflow_text as text

In [ ]:
docs = tf.constant([u'Everything not saved will be lost.'.encode('UTF-16-BE'), u'Sad☹'.encode('UTF-16-BE')])
utf8_docs = tf.strings.unicode_transcode(docs, input_encoding='UTF-16-BE', output_encoding='UTF-8')
utf8_docs

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'Everything not saved will be lost.', b'Sad\xe2\x98\xb9'],
      dtype=object)>

In [ ]:
tokenizer = text.WhitespaceTokenizer()
tokens = tokenizer.tokenize(['everything not saved will be lost.', u'Sad☹'.encode('UTF-8')])
print(tokens.to_list())

[[b'everything', b'not', b'saved', b'will', b'be', b'lost.'], [b'Sad\xe2\x98\xb9']]
