<a href="https://colab.research.google.com/github/Philippe-AD/Jupyter/blob/master/CorPDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#mount Google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#read-PDF imports here
!pip install PyPDF2
import PyPDF2

#pre-processing imports here
import re
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import string

In [ ]:
#file locations on drive
grimm_url = '/content/drive/My Drive/Lessons/storyTeller/FairytalesByTheBrothersGrimm.txt'
coraline_url = '/content/drive/My Drive/Lessons/storyTeller/Coraline.pdf'
alice_url = '/content/drive/My Drive/Lessons/storyTeller/AlicesAdvanturesInWonderland.txt'

In [ ]:
#a function to pre process Coraline by Neil Gaiman

def preprocess_coraline(book):
  '''
  param book: url od a PDF book file
  '''
  output = ""
  data = open(book, 'rb')
  data = PyPDF2.PdfFileReader(book)
  npages = data.getNumPages()
  for i in range(npages):
    page_i = data.getPage(i).extractText()
    output += page_i

  output = output[1227:]
  output = output.lower()
  
  processed = word_tokenize(output)
  print('Coraline database includes {} tokens, and {} unique tokens after editing'.format(len(processed), len(set(processed)))) 
  return processed

coraline = preprocess_coraline(coraline_url) 
print(coraline)
output = coraline 

Coraline database includes 38123 tokens, and 3454 unique tokens after editing
['coraline', 'discovered', 'the', 'door', 'a', 'little', 'while', 'after', 'they', 'moved', 'into', 'the', 'house', '.', 'it', 'was', 'a', 'very', 'old', 'housešit', 'had', 'an', 'attic', 'under', 'the', 'roof', 'and', 'a', 'cellar', 'under', 'the', 'ground', 'and', 'an', 'overgrown', 'garden', 'with', 'huge', 'old', 'trees', 'in', 'it', '.', 'coraline', "'s", 'family', 'did', "n't", 'own', 'all', 'of', 'the', 'housešit', 'was', 'too', 'big', 'for', 'that', '.', 'instead', 'they', 'owned', 'part', 'of', 'it', '.', 'there', 'were', 'other', 'people', 'who', 'lived', 'in', 'the', 'old', 'house', '.', 'miss', 'spink', 'and', 'miss', 'forcible', 'lived', 'in', 'the', 'flat', 'below', 'coraline', "'s", ',', 'on', 'the', 'ground', 'floor', '.', 'they', 'were', 'both', 'old', 'and', 'round', ',', 'and', 'they', 'lived', 'in', 'their', 'flat', 'with', 'a', 'number', 'of', 'ageing', 'highland', 'terriers', 'who', 'had

In [ ]:
print(type(output))
IndefinitePronouns = ["all", "another", "any", "anybody", "anyone", "anything", "both", "each", "either", "everybody", "everyone", "everything", "few", "many", "most", "neither", "nobody", "none", "no-one", "nothing", "one", "other", "others", "several", "some", "somebody", "someone", "something", "such" ]


for x in range(len(output[:38000])):
  a,b,c,d,e,f,g,h,i = output[x], output[x+1], output[x+2], output[x+3], output[x+4], output[x+5], output[x+6], output[x+7], output[x+8]
  if e in IndefinitePronouns:
    print(x,':  ',a,b,c,d,'<strong>'+e+'</strong>',f,g,h,i,'<br />')



<class 'list'>
45 :   family did n't own <strong>all</strong> of the housešit was <br />
64 :   it . there were <strong>other</strong> people who lived in <br />
93 :   floor . they were <strong>both</strong> old and round , <br />
164 :   name wrong , `` <strong>both</strong> myself and miss forcible <br />
199 :   he 'll be up <strong>all</strong> night with his tummy <br />
256 :   he would n't let <strong>anyone</strong> see it . `` <br />
261 :   see it . `` <strong>one</strong> day , little caroline <br />
270 :   , when they are <strong>all</strong> ready , everyone in <br />
273 :   are all ready , <strong>everyone</strong> in the whole world <br />
372 :   written for them . <strong>all</strong> the songs i have <br />
468 :   tennis court , but <strong>no-one</strong> in the house played <br />
512 :   a rockery that was <strong>all</strong> rocks ; there was <br />
650 :   boards , to stop <strong>anyone</strong> falling in . there <br />
660 :   a small knot-hole in <strong

Voir https://medium.com/@paritosh_30025/natural-language-processing-text-data-vectorization-af2520529cf7

Natural Language Processing: Text Data Vectorization
Paritosh Pantola
Paritosh Pantola
Jun 14, 2018·9 min read

UNDERSTANDING FEATURE ENGINEERING (PART 3)
Traditional Methods for Text Data
Traditional strategies for taming unstructured, textual data

Ultimate guide to deal with Text Data (using Python) – for Data Scientists and Engineers





# Feature Transformation of Text Data — NLP

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
corpus = [
'This movie is very scary and long',
'This movie is not scary and is slow',
'This movie is spooky and good',
 ]
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()

# words in vocablary and order in which feature are arranged
output : ['and', 'good', 'is', 'long', 'movie', 'not',
          'scary', 'slow', 'spooky', 'this', 'very']

X.toarray()
#Document represented in BOW binary Vector format


array([[1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0]])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(binary=True)
corpus = [
'This movie is very scary and long',
'This movie is not scary and is slow',
'This movie is spooky and good',
 ]
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()

# words in vocablary and order in which feature are arranged
output : ['and', 'good', 'is', 'long', 'movie', 'not',
          'scary', 'slow', 'spooky', 'this', 'very']

X.toarray()

array([[0.29628336, 0.        , 0.29628336, 0.50165133, 0.29628336,
        0.        , 0.38151877, 0.        , 0.        , 0.29628336,
        0.50165133],
       [0.29628336, 0.        , 0.29628336, 0.        , 0.29628336,
        0.50165133, 0.38151877, 0.50165133, 0.        , 0.29628336,
        0.        ],
       [0.32052772, 0.54270061, 0.32052772, 0.        , 0.32052772,
        0.        , 0.        , 0.        , 0.54270061, 0.32052772,
        0.        ]])

In [ ]:
import tensorflow as tf
import numpy as np
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(1000, 3, input_length=4))
# The model will take as input an integer matrix of size (batch,  
# input_length), and the largest integer (i.e. word index) in the input  
# should be no larger than 999 (vocabulary size).  
# Now model.output_shape is (2, 4, 3)
input_array = np.random.randint(1000, size=(2, 4))
print(input_array)

output_array = model.predict(input_array)
print(output_array)

[[688 225  62  91]
 [442 753 754 509]]
[[[ 0.00448768 -0.01288052  0.01131641]
  [-0.03633642 -0.000477    0.04499661]
  [-0.02428243 -0.03572013 -0.01375629]
  [ 0.0099107   0.02727484  0.01074211]]

 [[ 0.04240625  0.03659055 -0.00246956]
  [-0.01169679 -0.04572138  0.03941292]
  [-0.00345042  0.02164212 -0.03725773]
  [ 0.01597688 -0.00572779 -0.03506296]]]




---



In [ ]:
import tensorflow as tf

# Create a `Sequential` model and add a Dense layer as the first layer.  
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(16,)))
model.add(tf.keras.layers.Dense(32, activation='relu'))

# Now the model will take as input arrays of shape (None, 16)  
# and output arrays of shape (None, 32).  
# Note that after the first layer, you don't need to specify  
# the size of the input anymore:  

model.add(tf.keras.layers.Dense(32))
model.output_shape

(None, 32)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential(
    [
        Dense(5, activation="relu"),
        Dense(10, activation="relu"),
        Dense(15),
    ]
)  # No weights to be addded here

# Here we cannot check for weights
# model.weights

# Neither we can look at the summary
# model.summary()

# First we must call the model and evaluate it on test data
x = tf.ones((5, 20))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))

# Looking at the Summary of the Model
model.summary()

Number of weights after calling the model: 6
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (5, 5)                    105       
_________________________________________________________________
dense_6 (Dense)              (5, 10)                   60        
_________________________________________________________________
dense_7 (Dense)              (5, 15)                   165       
Total params: 330
Trainable params: 330
Non-trainable params: 0
_________________________________________________________________


https://machinelearningknowledge.ai/keras-tokenizer-tutorial-with-examples-for-fit_on_texts-texts_to_sequences-texts_to_matrix-sequences_to_matrix/

rien compris !

In [ ]:
from keras.preprocessing.text import Tokenizer

t  = Tokenizer()
# Defining 4 document lists
fit_text = ['Machine Learning Knowledge',
	          'Machine Learning',
            'Deep Learning',
            'Artificial Intelligence']

t.fit_on_texts(fit_text)
print("The document count",t.document_count)
print("The count of words",t.word_counts)
print("The word index",t.word_index)
print("The word docs",t.word_docs)

The document count 4
The count of words OrderedDict([('machine', 2), ('learning', 3), ('knowledge', 1), ('deep', 1), ('artificial', 1), ('intelligence', 1)])
The word index {'learning': 1, 'machine': 2, 'knowledge': 3, 'deep': 4, 'artificial': 5, 'intelligence': 6}
The word docs defaultdict(<class 'int'>, {'knowledge': 1, 'machine': 2, 'learning': 3, 'deep': 1, 'intelligence': 1, 'artificial': 1})


In [ ]:
t = Tokenizer()

test_text = ['Machine Learning Knowledge',
	          'Machine Learning',
            'Deep Learning',
            'Artificial Intelligence']

t.fit_on_texts(test_text)

sequences = t.texts_to_sequences(test_text)

print("The sequences generated from text are : ",sequences)

The sequences generated from text are :  [[2, 1, 3], [2, 1], [4, 1], [5, 6]]


In [ ]:
# define 5 documents
docs = ['Marvellous Machine Learning Marvellous Machine Learning',
		'Amazing Artificial Intelligence',
		'Dazzling Deep Learning',
		'Champion Computer Vision',
		'Notorious Natural Language Processing Notorious Natural Language Processing']
# create the tokenizer
t = Tokenizer()

t.fit_on_texts(docs)

encoded_docs = t.texts_to_matrix(docs, mode='binary')
print(encoded_docs)

[[0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# define 5 documents 
docs = ['Marvellous Machine Learning Marvellous Machine Learning', 
'Amazing Artificial Intelligence', 
'Dazzling Deep Learning', 
'Champion Computer Vision', 
'Notorious Natural Language Processing Notorious Natural Language Processing'] 

# create the tokenizer
t = Tokenizer()

t.fit_on_texts(docs)

encoded_docs = t.texts_to_matrix(docs, mode='count')

print(encoded_docs)

[[0. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
t.fit_on_texts(docs)
encoded_docs = t.texts_to_matrix(docs, mode='tfidf')
print(encoded_docs)

[[0.         1.8601123  2.48272447 2.48272447 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         1.46633707 1.46633707 1.46633707 0.
  0.         0.         0.         0.        ]
 [0.         1.09861229 0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.46633707
  1.46633707 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         1.46633707 1.46633707 1.46633707]
 [0.         0.         0.         0.         2.48272447 2.48272447
  2.48272447 2.48272447 0.         0.         0.         0.
  0.         0.         0.         0.        ]]


In [ ]:
t.fit_on_texts(docs)

encoded_docs = t.texts_to_matrix(docs, mode='freq')

print(encoded_docs)

[[0.         0.33333333 0.33333333 0.33333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.33333333 0.33333333 0.33333333 0.
  0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.33333333
  0.33333333 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.33333333 0.33333333 0.33333333]
 [0.         0.         0.         0.         0.25       0.25
  0.25       0.25       0.         0.         0.         0.
  0.         0.         0.         0.        ]]


In [ ]:
# define 4 documents
docs =['Machine Learning Knowledge',
       'Machine Learning and Deep Learning',
       'Deep Learning',
       'Artificial Intelligence']

# create the tokenizer
t = Tokenizer()

t.fit_on_texts(docs)

sequences = t.texts_to_sequences(docs)

encoded_docs = t.sequences_to_matrix(sequences, mode='binary')
print(encoded_docs)

[[0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]]
